import type { Metadata } from "next";
import { ProfileCard } from "../components/profilecard";
import "./globals.css";

export const metadata: Metadata = {
  title: "WebDev Challenger",
  description: "Generated by dedication",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
