import type { Metadata } from "next";
import "./globals.css";

import { Roboto } from "next/font/google";

export const metadata: Metadata = {
  title: "WebDev Challenger",
  description: "Generated by dedication",
};

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
